### PR TITLE
Better behavior when no content is found

### PR DESCRIPTION
**Pull request by fdev31**
- same behavior for both files when there is no content (always avoid generating empty files)
- use `logging` for logs (instead of `warnings`)/ rework some messages

### CODE REVIEW

**Comment by fdev31** [comment]
If you like the change to "logging" module I can generalize it a bit more / make it a bit more clean.

**Comment by fdev31** [comment]
I made a couple of extra commits which I pushed on the same branch without thinking, tell me what you like or not and I'll separate the commits accordingly.

**Comment by fdev31** [comment]
I think the monochrome option is useless, it's like a slow PWM. I may do more tests... but not happy so far.

**Comment by johannesnoordanus** [comment]
I will look at this, but currently too busy with feature updates.

**Comment by johannesnoordanus** [comment]
I will look at this in the future, but some improvements are already done, others like "monochrome" are meant to influence the (B&W) image conversion. I am not sure that is a good idea,  but I think the least is to mention (output) what kind of conversion is done or if a conversion is none. I would also like to add a dithering/halftone option to set this effect after conversion (or as conversion) so that image resolution size differences cannot produce artefacts.
(The '--showimage' options show the image after conversion, so this makes it possible to evaluate the dithering/halftone effects (or resize), and option '--validate' shows the exact pixels (and B&W value) in gcode before you run it on a machine.
I might add '--validate' to svg2gcode to be able to do that consistently ...)

**Pull request closed without merging**
