### PR TITLE
add support for linked images

### PR DESCRIPTION
**Pull request by fdev31**
Supports image references (filename instead of base64 encoded data)

### CODE REVIEW

**Review by johannesnoordanus — APPROVED** [review]
Looks good!

**Comment by fdev31** [comment]
I just realized, in case the file is not in the same folder as the svg it will have the full path + "file://" prefix, so in this case we should change the limit for the length of the path to something like 4096 + 7 instead of 255...

**Comment by johannesnoordanus** [comment]
Ok, I will update that.

**Comment by johannesnoordanus** [comment]
We have a new version now (1.2) which includes this update.
It is also an interface change: removed option --maxlaserpower, changed option --cuttingpower (to be an int, instead of a fraction).
Also, bbox reporting (within the gcode files) has a different format (instead of ' to ', I use ':').

**Pull request merged**
